### ISSUE TITLE
incorrect copyright headers

### ISSUE THREAD

**Issue by danmarsden** [emeneo/moodle-format_event#1]
It looks like you've copied some basic structure from some other locations, but the tests/upgrade/privacy provider/backup files all look like you've left someone elses name in there under the copyright header - you should tidy that up. :-)

**Comment by Flottertotte** [comment]
Yeah, our plugin is based on the topics course format. Thanks for mentioning the two folders - we update that in one of the upcoming releases.

**Comment by danmarsden** [comment]
Cool - it would probably be good for to add a line to the readme in this code that states - this plugin is based on the core "topics" format - Just to help give "credit" to the original topic format dev.

**Comment by Flottertotte** [comment]
Done :)
