### ISSUE TITLE
features not clear in plugins db.

### ISSUE THREAD

**Issue by danmarsden** [emeneo/moodle-format_event#3]
When testing this plugin, it appeared to just reproduce the topics course format with the only difference I could see being that the course date was entered in the calendar. The screenshots in the plugins db don't make this clear and neither does the description in the plugins db.

in the plugins db you also mention "Drag & Drop calendar event in calendar --> change in course settings" - but it's not clear what this refers to or if it's a "new feature provided by your plugin at all?

**Comment by Flottertotte** [comment]
"Drag & Drop calendar event in calendar --> change in course settings" means, that if the calendar event is moved in the calendar via drag & drop, the date change is pushed back to the course settings. So if for example the admin wants to change the course date, she does not need to go to the course settings but can do that easily in the calendar (drag&drop the even). This is very useful, especially in the case of an organization that has to handle many events.

We have now slightly changed the description: 

> The course format "Event" is intended to be used for short training events. Upon course creation, it creates a corresponding calendar event.
>
>**Current Features:**
>
>- Calendar event creation upon course creation
>- The calendar event's start date/time, end date/time and description is taken from th course start date/time, end date/time and summary
>- If the calendar event is changed via  drag & drop, changes are pushed back to the related course settings
>
>**Roadmap**
>The course format "Event" is based on the course format "Topics". For the future, we plan the following:
>- hange the look and feel of the course page
>- Add Event specific course fields (such as location)
>
>Ideas and support welcome!

Hope it is better now :)

**Comment by danmarsden** [comment]
yeah - that's much better thanks! - feel free to close this when you're ready.
