### ISSUE TITLE
upgrade code blindly copied from topics format

### ISSUE THREAD

**Issue by danmarsden** [emeneo/moodle-format_event#6]
You shouldn't need the upgrade code you have copied from the topics format - I'd expect you could delete upgradelib.php and the steps in upgrade.php.

**Comment by Flottertotte** [comment]
Yeah, I have emptied the file now but - although not needed - would like to keep it for future usage.

**Comment by danmarsden** [comment]
the code you have left in upgrade.php will trigger some failiures in the code that checks upgrade.php as you have an empty "if" statement without a corresponding save version call:
```

    if ($oldversion < 2017020200) {
        // Version no above is just an example. Actions go in here.
 
    }
```
You should remove/comment that code out..

You should also delete the upgradelib.php file, or at the very least, remove the topics specific functions in there.

**Comment by Flottertotte** [comment]
Ok, all upgrade code has been deleted
